#360T7
name: Build MT7981 U-Boot 360T7 MultiLayout 108M
on:
  # 移除push，只保留手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source & submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install official required dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu build-essential flex bison libssl-dev device-tree-compiler qemu-user-static

      - name: Compile U-Boot support 108M UBI
        run: SOC=mt7981 BOARD=360t7 MULTI_LAYOUT=1 ./build.sh

      - name: Upload compiled uboot artifact
        uses: actions/upload-artifact@v4
        with:
          name: 360T7-UBOOT-MultiLayout-108M
          path: ./output/
          retention-days: 30
